export type SET_CART_PRODUCT_QUANTITY = 'SET_CART_PRODUCT_QUANTITY';
export const SET_CART_PRODUCT_QUANTITY = 'SET_CART_PRODUCT_QUANTITY';

export type TOGGLE_PRODUCT_FAVORITE = 'TOGGLE_PRODUCT_FAVORITE';
export const TOGGLE_PRODUCT_FAVORITE = 'TOGGLE_PRODUCT_FAVORITE';

export type ADD_ORIGIN_FILTER = 'ADD_ORIGIN_FILTER';
export const ADD_ORIGIN_FILTER = 'ADD_ORIGIN_FILTER';

export type REMOVE_ORIGIN_FILTER = 'REMOVE_ORIGIN_FILTER';
export const REMOVE_ORIGIN_FILTER = 'REMOVE_ORIGIN_FILTER';
