export type SET_CART_PRODUCT_QUANTITY = 'SET_CART_PRODUCT_QUANTITY';
export const SET_CART_PRODUCT_QUANTITY = 'SET_CART_PRODUCT_QUANTITY';

export type CLEAR_CART = 'CLEAR_CART';
export const CLEAR_CART = 'CLEAR_CART';


export type TOGGLE_PRODUCT_FAVORITE = 'TOGGLE_PRODUCT_FAVORITE';
export const TOGGLE_PRODUCT_FAVORITE = 'TOGGLE_PRODUCT_FAVORITE';


export type ADD_ORIGIN_FILTER = 'ADD_ORIGIN_FILTER';
export const ADD_ORIGIN_FILTER = 'ADD_ORIGIN_FILTER';

export type REMOVE_ORIGIN_FILTER = 'REMOVE_ORIGIN_FILTER';
export const REMOVE_ORIGIN_FILTER = 'REMOVE_ORIGIN_FILTER';

export type SET_FAVORITE_FILTER = 'SET_FAVORITE_FILTER';
export const SET_FAVORITE_FILTER = 'SET_FAVORITE_FILTER';

export type SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';

export type CLEAR_FILTERS = 'CLEAR_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';


export type EDIT_PAYMENT = 'EDIT_PAYMENT';
export const EDIT_PAYMENT = 'EDIT_PAYMENT';

export type EDIT_SHIPPING = 'EDIT_SHIPPING';
export const EDIT_SHIPPING = 'EDIT_SHIPPING';


export type ADD_TOAST = 'ADD_TOAST';
export const ADD_TOAST = 'ADD_TOAST';

export type REMOVE_TOAST = 'REMOVE_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

export type SET_PRODUCT_REMOVAL_UNDO_BUTTON_PRODUCT = 'SET_PRODUCT_REMOVAL_UNDO_BUTTON_PRODUCT';
export const SET_PRODUCT_REMOVAL_UNDO_BUTTON_PRODUCT = 'SET_PRODUCT_REMOVAL_UNDO_BUTTON_PRODUCT';

export type UNDO_LAST_CART_REMOVAL = 'UNDO_LAST_CART_REMOVAL';
export const UNDO_LAST_CART_REMOVAL = 'UNDO_LAST_CART_REMOVAL';
